services:
  mysql:
    image: mysql:8.3.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_DB: keycloak
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak
    command: [ "start-dev", "--import-realm" ]
    ports:
      - "8090:8080"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    depends_on:
      - mysql

volumes:
  keycloak_data:
  mysql_data: