services:
  MySqlDataBase:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE : userdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql